apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-deployment
spec:
  selector:
    matchLabels:
      app: angular
  replicas: 2
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
      - name: angular
        image: houssemdocker/angular-app:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
